from __future__ import annotations


APP_TITLE = "Datajson"
DEFAULT_JSONL = (
    "/Users/kalami/Keyan/dllm/Work01-data收集/datapipeline/"
    "01_格式转换/Weave/weave_interleaved_en.jsonl"
)

IMAGE_EXTS = (".jpg", ".jpeg", ".png", ".webp", ".gif", ".bmp", ".tif", ".tiff")
IMAGE_KEYS = {
    "asset_path",
    "assets",
    "image",
    "image_file",
    "image_filename",
    "image_uri",
    "image_url",
    "image_urls",
    "images",
    "img",
    "imgs",
    "img_path",
    "img_url",
    "photo",
    "photos",
    "picture",
    "pictures",
    "pic",
    "src",
    "media_path",
    "local_path",
    "relative_path",
    "original_image",
    "original_images",
    "original_path",
    "source_image",
    "source_images",
    "input_image",
    "input_images",
    "filepath",
    "file_path",
    "file",
    "files",
    "image_path",
    "path",
    "url",
    "uri",
    "data_url",
    "data_uri",
    "bytes",
    "filename",
    "file_name",
}
TEXT_KEYS = {
    "text",
    "caption",
    "prompt",
    "instruction",
    "input",
    "output",
    "human",
    "assistant",
    "system",
    "question",
    "answer",
    "response",
    "content",
    "value",
    "description",
    "query",
    "query_text",
    "answer_text",
    "ocr",
    "ground_truth",
    "title",
}
COLLECTION_KEYS = {
    "data",
    "samples",
    "items",
    "records",
    "instances",
    "examples",
    "rows",
    "annotations",
    "dataset",
}
